# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gs_shortcuts.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(598, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(598, 380))
        Form.setMaximumSize(QtCore.QSize(598, 380))
        Form.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/cat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QComboBox::drop-down {\n"
"    width: 26px;\n"
"}\n"
"\n"
"")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(307, 310, 273, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setStyleSheet("border-image: url(media/button.png);\n"
"font: 16pt \"黑体\";\n"
"color:white;font: bold;")
        self.pushButton_2.setShortcut("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 310, 273, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setStyleSheet("border-image: url(media/button.png);\n"
"font: 16pt \"黑体\";\n"
"color:white;font: bold;")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 30, 561, 271))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.comboBox_gamemode4 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_gamemode4.setGeometry(QtCore.QRect(110, 15, 180, 36))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_gamemode4.setFont(font)
        self.comboBox_gamemode4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"width:120px;\n"
"height: 32px;\n"
"color: #3d3d3d;\n"
"\n"
"")
        self.comboBox_gamemode4.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_gamemode4.setObjectName("comboBox_gamemode4")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.spinBox_minenum4 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_minenum4.setGeometry(QtCore.QRect(110, 100, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_minenum4.setFont(font)
        self.spinBox_minenum4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_minenum4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_minenum4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_minenum4.setKeyboardTracking(True)
        self.spinBox_minenum4.setProperty("showGroupSeparator", False)
        self.spinBox_minenum4.setMaximum(999)
        self.spinBox_minenum4.setProperty("value", 72)
        self.spinBox_minenum4.setObjectName("spinBox_minenum4")
        self.spinBox_attempt_times_limit4 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_attempt_times_limit4.setGeometry(QtCore.QRect(138, 180, 132, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_attempt_times_limit4.sizePolicy().hasHeightForWidth())
        self.spinBox_attempt_times_limit4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_attempt_times_limit4.setFont(font)
        self.spinBox_attempt_times_limit4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_attempt_times_limit4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_attempt_times_limit4.setFrame(True)
        self.spinBox_attempt_times_limit4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_attempt_times_limit4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_attempt_times_limit4.setKeyboardTracking(True)
        self.spinBox_attempt_times_limit4.setProperty("showGroupSeparator", False)
        self.spinBox_attempt_times_limit4.setMinimum(0)
        self.spinBox_attempt_times_limit4.setMaximum(99999999)
        self.spinBox_attempt_times_limit4.setProperty("value", 99999999)
        self.spinBox_attempt_times_limit4.setObjectName("spinBox_attempt_times_limit4")
        self.lineEdit_constraint4 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_constraint4.setGeometry(QtCore.QRect(138, 140, 401, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_constraint4.setFont(font)
        self.lineEdit_constraint4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_constraint4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.lineEdit_constraint4.setText("")
        self.lineEdit_constraint4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_constraint4.setObjectName("lineEdit_constraint4")
        self.spinBox_width4 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_width4.setGeometry(QtCore.QRect(378, 60, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_width4.setFont(font)
        self.spinBox_width4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_width4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_width4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_width4.setKeyboardTracking(True)
        self.spinBox_width4.setProperty("showGroupSeparator", False)
        self.spinBox_width4.setMinimum(6)
        self.spinBox_width4.setMaximum(1000)
        self.spinBox_width4.setProperty("value", 16)
        self.spinBox_width4.setObjectName("spinBox_width4")
        self.spinBox_height4 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_height4.setGeometry(QtCore.QRect(110, 60, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_height4.setFont(font)
        self.spinBox_height4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_height4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_height4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_height4.setKeyboardTracking(True)
        self.spinBox_height4.setProperty("showGroupSeparator", False)
        self.spinBox_height4.setMinimum(6)
        self.spinBox_height4.setMaximum(1000)
        self.spinBox_height4.setProperty("value", 16)
        self.spinBox_height4.setObjectName("spinBox_height4")
        self.spinBox_pixsize4 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_pixsize4.setGeometry(QtCore.QRect(378, 100, 160, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_pixsize4.sizePolicy().hasHeightForWidth())
        self.spinBox_pixsize4.setSizePolicy(sizePolicy)
        self.spinBox_pixsize4.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_pixsize4.setFont(font)
        self.spinBox_pixsize4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_pixsize4.setFrame(True)
        self.spinBox_pixsize4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_pixsize4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_pixsize4.setKeyboardTracking(True)
        self.spinBox_pixsize4.setProperty("showGroupSeparator", False)
        self.spinBox_pixsize4.setMinimum(1)
        self.spinBox_pixsize4.setMaximum(200)
        self.spinBox_pixsize4.setProperty("value", 20)
        self.spinBox_pixsize4.setObjectName("spinBox_pixsize4")
        self.label_gamemode4 = QtWidgets.QLabel(self.tab_4)
        self.label_gamemode4.setGeometry(QtCore.QRect(20, 13, 61, 39))
        self.label_gamemode4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_gamemode4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_gamemode4.setObjectName("label_gamemode4")
        self.label_constraint4 = QtWidgets.QLabel(self.tab_4)
        self.label_constraint4.setGeometry(QtCore.QRect(20, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_constraint4.setFont(font)
        self.label_constraint4.setScaledContents(False)
        self.label_constraint4.setWordWrap(False)
        self.label_constraint4.setObjectName("label_constraint4")
        self.label_minenum4 = QtWidgets.QLabel(self.tab_4)
        self.label_minenum4.setGeometry(QtCore.QRect(20, 100, 61, 32))
        self.label_minenum4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_minenum4.setObjectName("label_minenum4")
        self.label_height4 = QtWidgets.QLabel(self.tab_4)
        self.label_height4.setGeometry(QtCore.QRect(20, 59, 61, 32))
        self.label_height4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_height4.setObjectName("label_height4")
        self.label_attempt_times_limit4 = QtWidgets.QLabel(self.tab_4)
        self.label_attempt_times_limit4.setGeometry(QtCore.QRect(20, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_attempt_times_limit4.setFont(font)
        self.label_attempt_times_limit4.setScaledContents(False)
        self.label_attempt_times_limit4.setWordWrap(False)
        self.label_attempt_times_limit4.setObjectName("label_attempt_times_limit4")
        self.label_width4 = QtWidgets.QLabel(self.tab_4)
        self.label_width4.setGeometry(QtCore.QRect(290, 59, 61, 32))
        self.label_width4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_width4.setObjectName("label_width4")
        self.label_pixsize4 = QtWidgets.QLabel(self.tab_4)
        self.label_pixsize4.setGeometry(QtCore.QRect(290, 100, 61, 32))
        self.label_pixsize4.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_pixsize4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_pixsize4.setObjectName("label_pixsize4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.comboBox_gamemode5 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_gamemode5.setGeometry(QtCore.QRect(110, 15, 180, 36))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_gamemode5.setFont(font)
        self.comboBox_gamemode5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"width:120px;\n"
"height: 32px;\n"
"color: #3d3d3d;\n"
"\n"
"")
        self.comboBox_gamemode5.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_gamemode5.setObjectName("comboBox_gamemode5")
        self.comboBox_gamemode5.addItem("")
        self.comboBox_gamemode5.addItem("")
        self.comboBox_gamemode5.addItem("")
        self.comboBox_gamemode5.addItem("")
        self.comboBox_gamemode5.addItem("")
        self.comboBox_gamemode5.addItem("")
        self.comboBox_gamemode5.addItem("")
        self.comboBox_gamemode5.addItem("")
        self.spinBox_minenum5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_minenum5.setGeometry(QtCore.QRect(110, 100, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_minenum5.setFont(font)
        self.spinBox_minenum5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_minenum5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_minenum5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_minenum5.setKeyboardTracking(True)
        self.spinBox_minenum5.setProperty("showGroupSeparator", False)
        self.spinBox_minenum5.setMaximum(999)
        self.spinBox_minenum5.setProperty("value", 72)
        self.spinBox_minenum5.setObjectName("spinBox_minenum5")
        self.spinBox_attempt_times_limit5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_attempt_times_limit5.setGeometry(QtCore.QRect(138, 180, 132, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_attempt_times_limit5.sizePolicy().hasHeightForWidth())
        self.spinBox_attempt_times_limit5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_attempt_times_limit5.setFont(font)
        self.spinBox_attempt_times_limit5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_attempt_times_limit5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_attempt_times_limit5.setFrame(True)
        self.spinBox_attempt_times_limit5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_attempt_times_limit5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_attempt_times_limit5.setKeyboardTracking(True)
        self.spinBox_attempt_times_limit5.setProperty("showGroupSeparator", False)
        self.spinBox_attempt_times_limit5.setMinimum(0)
        self.spinBox_attempt_times_limit5.setMaximum(99999999)
        self.spinBox_attempt_times_limit5.setProperty("value", 99999999)
        self.spinBox_attempt_times_limit5.setObjectName("spinBox_attempt_times_limit5")
        self.lineEdit_constraint5 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_constraint5.setGeometry(QtCore.QRect(138, 140, 401, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_constraint5.setFont(font)
        self.lineEdit_constraint5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_constraint5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.lineEdit_constraint5.setText("")
        self.lineEdit_constraint5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_constraint5.setObjectName("lineEdit_constraint5")
        self.spinBox_width5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_width5.setGeometry(QtCore.QRect(378, 60, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_width5.setFont(font)
        self.spinBox_width5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_width5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_width5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_width5.setKeyboardTracking(True)
        self.spinBox_width5.setProperty("showGroupSeparator", False)
        self.spinBox_width5.setMinimum(6)
        self.spinBox_width5.setMaximum(1000)
        self.spinBox_width5.setProperty("value", 16)
        self.spinBox_width5.setObjectName("spinBox_width5")
        self.spinBox_height5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_height5.setGeometry(QtCore.QRect(110, 60, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_height5.setFont(font)
        self.spinBox_height5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_height5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_height5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_height5.setKeyboardTracking(True)
        self.spinBox_height5.setProperty("showGroupSeparator", False)
        self.spinBox_height5.setMinimum(6)
        self.spinBox_height5.setMaximum(1000)
        self.spinBox_height5.setProperty("value", 16)
        self.spinBox_height5.setObjectName("spinBox_height5")
        self.spinBox_pixsize5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_pixsize5.setGeometry(QtCore.QRect(378, 100, 160, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_pixsize5.sizePolicy().hasHeightForWidth())
        self.spinBox_pixsize5.setSizePolicy(sizePolicy)
        self.spinBox_pixsize5.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_pixsize5.setFont(font)
        self.spinBox_pixsize5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_pixsize5.setFrame(True)
        self.spinBox_pixsize5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_pixsize5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_pixsize5.setKeyboardTracking(True)
        self.spinBox_pixsize5.setProperty("showGroupSeparator", False)
        self.spinBox_pixsize5.setMinimum(1)
        self.spinBox_pixsize5.setMaximum(200)
        self.spinBox_pixsize5.setProperty("value", 20)
        self.spinBox_pixsize5.setObjectName("spinBox_pixsize5")
        self.label_gamemode5 = QtWidgets.QLabel(self.tab_3)
        self.label_gamemode5.setGeometry(QtCore.QRect(20, 13, 71, 39))
        self.label_gamemode5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_gamemode5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_gamemode5.setObjectName("label_gamemode5")
        self.label_constraint5 = QtWidgets.QLabel(self.tab_3)
        self.label_constraint5.setGeometry(QtCore.QRect(20, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_constraint5.setFont(font)
        self.label_constraint5.setScaledContents(False)
        self.label_constraint5.setWordWrap(False)
        self.label_constraint5.setObjectName("label_constraint5")
        self.label_minenum5 = QtWidgets.QLabel(self.tab_3)
        self.label_minenum5.setGeometry(QtCore.QRect(20, 100, 71, 32))
        self.label_minenum5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_minenum5.setObjectName("label_minenum5")
        self.label_height5 = QtWidgets.QLabel(self.tab_3)
        self.label_height5.setGeometry(QtCore.QRect(20, 59, 71, 32))
        self.label_height5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_height5.setObjectName("label_height5")
        self.label_attempt_times_limit5 = QtWidgets.QLabel(self.tab_3)
        self.label_attempt_times_limit5.setGeometry(QtCore.QRect(20, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_attempt_times_limit5.setFont(font)
        self.label_attempt_times_limit5.setScaledContents(False)
        self.label_attempt_times_limit5.setWordWrap(False)
        self.label_attempt_times_limit5.setObjectName("label_attempt_times_limit5")
        self.label_width5 = QtWidgets.QLabel(self.tab_3)
        self.label_width5.setGeometry(QtCore.QRect(290, 59, 71, 32))
        self.label_width5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_width5.setObjectName("label_width5")
        self.label_pixsize5 = QtWidgets.QLabel(self.tab_3)
        self.label_pixsize5.setGeometry(QtCore.QRect(290, 100, 71, 32))
        self.label_pixsize5.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_pixsize5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_pixsize5.setObjectName("label_pixsize5")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_41 = QtWidgets.QWidget()
        self.tab_41.setObjectName("tab_41")
        self.spinBox_attempt_times_limit6 = QtWidgets.QSpinBox(self.tab_41)
        self.spinBox_attempt_times_limit6.setGeometry(QtCore.QRect(138, 180, 132, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_attempt_times_limit6.sizePolicy().hasHeightForWidth())
        self.spinBox_attempt_times_limit6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_attempt_times_limit6.setFont(font)
        self.spinBox_attempt_times_limit6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_attempt_times_limit6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_attempt_times_limit6.setFrame(True)
        self.spinBox_attempt_times_limit6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_attempt_times_limit6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_attempt_times_limit6.setKeyboardTracking(True)
        self.spinBox_attempt_times_limit6.setProperty("showGroupSeparator", False)
        self.spinBox_attempt_times_limit6.setMinimum(0)
        self.spinBox_attempt_times_limit6.setMaximum(99999999)
        self.spinBox_attempt_times_limit6.setProperty("value", 99999999)
        self.spinBox_attempt_times_limit6.setObjectName("spinBox_attempt_times_limit6")
        self.comboBox_gamemode6 = QtWidgets.QComboBox(self.tab_41)
        self.comboBox_gamemode6.setGeometry(QtCore.QRect(110, 15, 180, 36))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_gamemode6.setFont(font)
        self.comboBox_gamemode6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"width:120px;\n"
"height: 32px;\n"
"color: #3d3d3d;\n"
"\n"
"")
        self.comboBox_gamemode6.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_gamemode6.setObjectName("comboBox_gamemode6")
        self.comboBox_gamemode6.addItem("")
        self.comboBox_gamemode6.addItem("")
        self.comboBox_gamemode6.addItem("")
        self.comboBox_gamemode6.addItem("")
        self.comboBox_gamemode6.addItem("")
        self.comboBox_gamemode6.addItem("")
        self.comboBox_gamemode6.addItem("")
        self.comboBox_gamemode6.addItem("")
        self.label_height6 = QtWidgets.QLabel(self.tab_41)
        self.label_height6.setGeometry(QtCore.QRect(20, 59, 61, 32))
        self.label_height6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_height6.setObjectName("label_height6")
        self.label_width6 = QtWidgets.QLabel(self.tab_41)
        self.label_width6.setGeometry(QtCore.QRect(290, 59, 61, 32))
        self.label_width6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_width6.setObjectName("label_width6")
        self.spinBox_height6 = QtWidgets.QSpinBox(self.tab_41)
        self.spinBox_height6.setGeometry(QtCore.QRect(110, 60, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_height6.setFont(font)
        self.spinBox_height6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_height6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_height6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_height6.setKeyboardTracking(True)
        self.spinBox_height6.setProperty("showGroupSeparator", False)
        self.spinBox_height6.setMinimum(6)
        self.spinBox_height6.setMaximum(1000)
        self.spinBox_height6.setProperty("value", 16)
        self.spinBox_height6.setObjectName("spinBox_height6")
        self.label_attempt_times_limit6 = QtWidgets.QLabel(self.tab_41)
        self.label_attempt_times_limit6.setGeometry(QtCore.QRect(20, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_attempt_times_limit6.setFont(font)
        self.label_attempt_times_limit6.setScaledContents(False)
        self.label_attempt_times_limit6.setWordWrap(False)
        self.label_attempt_times_limit6.setObjectName("label_attempt_times_limit6")
        self.label_pixsize6 = QtWidgets.QLabel(self.tab_41)
        self.label_pixsize6.setGeometry(QtCore.QRect(290, 100, 61, 32))
        self.label_pixsize6.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_pixsize6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_pixsize6.setObjectName("label_pixsize6")
        self.spinBox_width6 = QtWidgets.QSpinBox(self.tab_41)
        self.spinBox_width6.setGeometry(QtCore.QRect(378, 60, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_width6.setFont(font)
        self.spinBox_width6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_width6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_width6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_width6.setKeyboardTracking(True)
        self.spinBox_width6.setProperty("showGroupSeparator", False)
        self.spinBox_width6.setMinimum(6)
        self.spinBox_width6.setMaximum(1000)
        self.spinBox_width6.setProperty("value", 16)
        self.spinBox_width6.setObjectName("spinBox_width6")
        self.label_gamemode6 = QtWidgets.QLabel(self.tab_41)
        self.label_gamemode6.setGeometry(QtCore.QRect(20, 13, 61, 39))
        self.label_gamemode6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_gamemode6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_gamemode6.setObjectName("label_gamemode6")
        self.spinBox_pixsize6 = QtWidgets.QSpinBox(self.tab_41)
        self.spinBox_pixsize6.setGeometry(QtCore.QRect(378, 100, 160, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_pixsize6.sizePolicy().hasHeightForWidth())
        self.spinBox_pixsize6.setSizePolicy(sizePolicy)
        self.spinBox_pixsize6.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_pixsize6.setFont(font)
        self.spinBox_pixsize6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_pixsize6.setFrame(True)
        self.spinBox_pixsize6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_pixsize6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_pixsize6.setKeyboardTracking(True)
        self.spinBox_pixsize6.setProperty("showGroupSeparator", False)
        self.spinBox_pixsize6.setMinimum(1)
        self.spinBox_pixsize6.setMaximum(200)
        self.spinBox_pixsize6.setProperty("value", 20)
        self.spinBox_pixsize6.setObjectName("spinBox_pixsize6")
        self.spinBox_minenum6 = QtWidgets.QSpinBox(self.tab_41)
        self.spinBox_minenum6.setGeometry(QtCore.QRect(110, 100, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_minenum6.setFont(font)
        self.spinBox_minenum6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_minenum6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_minenum6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_minenum6.setKeyboardTracking(True)
        self.spinBox_minenum6.setProperty("showGroupSeparator", False)
        self.spinBox_minenum6.setMaximum(999)
        self.spinBox_minenum6.setProperty("value", 72)
        self.spinBox_minenum6.setObjectName("spinBox_minenum6")
        self.lineEdit_constraint6 = QtWidgets.QLineEdit(self.tab_41)
        self.lineEdit_constraint6.setGeometry(QtCore.QRect(138, 140, 401, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_constraint6.setFont(font)
        self.lineEdit_constraint6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_constraint6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.lineEdit_constraint6.setText("")
        self.lineEdit_constraint6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_constraint6.setObjectName("lineEdit_constraint6")
        self.label_minenum6 = QtWidgets.QLabel(self.tab_41)
        self.label_minenum6.setGeometry(QtCore.QRect(20, 100, 61, 32))
        self.label_minenum6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_minenum6.setObjectName("label_minenum6")
        self.label_constraint6 = QtWidgets.QLabel(self.tab_41)
        self.label_constraint6.setGeometry(QtCore.QRect(20, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_constraint6.setFont(font)
        self.label_constraint6.setScaledContents(False)
        self.label_constraint6.setWordWrap(False)
        self.label_constraint6.setObjectName("label_constraint6")
        self.tabWidget.addTab(self.tab_41, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_gamemode4.setCurrentIndex(4)
        self.comboBox_gamemode5.setCurrentIndex(4)
        self.comboBox_gamemode6.setCurrentIndex(4)
        self.pushButton_2.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "快捷键设置"))
        self.pushButton_2.setText(_translate("Form", "取消"))
        self.pushButton.setText(_translate("Form", "确定"))
        self.comboBox_gamemode4.setItemText(0, _translate("Form", "标准"))
        self.comboBox_gamemode4.setItemText(1, _translate("Form", "Win7"))
        self.comboBox_gamemode4.setItemText(2, _translate("Form", "强无猜"))
        self.comboBox_gamemode4.setItemText(3, _translate("Form", "弱无猜"))
        self.comboBox_gamemode4.setItemText(4, _translate("Form", "竞速无猜"))
        self.comboBox_gamemode4.setItemText(5, _translate("Form", "准无猜"))
        self.comboBox_gamemode4.setItemText(6, _translate("Form", "强可猜"))
        self.comboBox_gamemode4.setItemText(7, _translate("Form", "弱可猜"))
        self.label_gamemode4.setText(_translate("Form", "模式："))
        self.label_constraint4.setText(_translate("Form", "局面约束："))
        self.label_minenum4.setText(_translate("Form", "雷数："))
        self.label_height4.setText(_translate("Form", "高度："))
        self.label_attempt_times_limit4.setText(_translate("Form", "尝试次数："))
        self.label_width4.setText(_translate("Form", "宽度："))
        self.label_pixsize4.setText(_translate("Form", "边长："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "快捷键[4]"))
        self.comboBox_gamemode5.setItemText(0, _translate("Form", "标准"))
        self.comboBox_gamemode5.setItemText(1, _translate("Form", "Win7"))
        self.comboBox_gamemode5.setItemText(2, _translate("Form", "强无猜"))
        self.comboBox_gamemode5.setItemText(3, _translate("Form", "弱无猜"))
        self.comboBox_gamemode5.setItemText(4, _translate("Form", "竞速无猜"))
        self.comboBox_gamemode5.setItemText(5, _translate("Form", "准无猜"))
        self.comboBox_gamemode5.setItemText(6, _translate("Form", "强可猜"))
        self.comboBox_gamemode5.setItemText(7, _translate("Form", "弱可猜"))
        self.label_gamemode5.setText(_translate("Form", "模式："))
        self.label_constraint5.setText(_translate("Form", "局面约束："))
        self.label_minenum5.setText(_translate("Form", "雷数："))
        self.label_height5.setText(_translate("Form", "高度："))
        self.label_attempt_times_limit5.setText(_translate("Form", "尝试次数："))
        self.label_width5.setText(_translate("Form", "宽度："))
        self.label_pixsize5.setText(_translate("Form", "边长："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "快捷键[5]"))
        self.comboBox_gamemode6.setItemText(0, _translate("Form", "标准"))
        self.comboBox_gamemode6.setItemText(1, _translate("Form", "Win7"))
        self.comboBox_gamemode6.setItemText(2, _translate("Form", "强无猜"))
        self.comboBox_gamemode6.setItemText(3, _translate("Form", "弱无猜"))
        self.comboBox_gamemode6.setItemText(4, _translate("Form", "竞速无猜"))
        self.comboBox_gamemode6.setItemText(5, _translate("Form", "准无猜"))
        self.comboBox_gamemode6.setItemText(6, _translate("Form", "强可猜"))
        self.comboBox_gamemode6.setItemText(7, _translate("Form", "弱可猜"))
        self.label_height6.setText(_translate("Form", "高度："))
        self.label_width6.setText(_translate("Form", "宽度："))
        self.label_attempt_times_limit6.setText(_translate("Form", "尝试次数："))
        self.label_pixsize6.setText(_translate("Form", "边长："))
        self.label_gamemode6.setText(_translate("Form", "模式："))
        self.label_minenum6.setText(_translate("Form", "雷数："))
        self.label_constraint6.setText(_translate("Form", "局面约束："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_41), _translate("Form", "快捷键[6]"))
