# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gs_shortcuts.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(620, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(620, 440))
        Form.setMaximumSize(QtCore.QSize(620, 440))
        Form.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/cat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QComboBox::drop-down {\n"
"    width: 26px;\n"
"}\n"
"\n"
"")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 380, 251, 41))
        self.pushButton_2.setStyleSheet("border-image: url(media/button.png);\n"
"font: 16pt \"黑体\";\n"
"color:white;font: bold;")
        self.pushButton_2.setShortcut("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 380, 251, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setStyleSheet("border-image: url(media/button.png);\n"
"font: 16pt \"黑体\";\n"
"color:white;font: bold;")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 30, 581, 331))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_height4 = QtWidgets.QLabel(self.tab_4)
        self.label_height4.setGeometry(QtCore.QRect(20, 100, 112, 32))
        self.label_height4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_height4.setObjectName("label_height4")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_3.setGeometry(QtCore.QRect(90, 100, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_3.setKeyboardTracking(True)
        self.spinBox_3.setProperty("showGroupSeparator", False)
        self.spinBox_3.setMaximum(999)
        self.spinBox_3.setProperty("value", 16)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_width4 = QtWidgets.QLabel(self.tab_4)
        self.label_width4.setGeometry(QtCore.QRect(20, 150, 112, 32))
        self.label_width4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_width4.setObjectName("label_width4")
        self.spinBox_4 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_4.setGeometry(QtCore.QRect(90, 150, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_4.setKeyboardTracking(True)
        self.spinBox_4.setProperty("showGroupSeparator", False)
        self.spinBox_4.setMaximum(999)
        self.spinBox_4.setProperty("value", 16)
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_minenum4 = QtWidgets.QLabel(self.tab_4)
        self.label_minenum4.setGeometry(QtCore.QRect(20, 200, 112, 32))
        self.label_minenum4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_minenum4.setObjectName("label_minenum4")
        self.spinBox_minenum4 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_minenum4.setGeometry(QtCore.QRect(90, 200, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_minenum4.setFont(font)
        self.spinBox_minenum4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_minenum4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_minenum4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_minenum4.setKeyboardTracking(True)
        self.spinBox_minenum4.setProperty("showGroupSeparator", False)
        self.spinBox_minenum4.setMaximum(999)
        self.spinBox_minenum4.setProperty("value", 72)
        self.spinBox_minenum4.setObjectName("spinBox_minenum4")
        self.label_pixsize4 = QtWidgets.QLabel(self.tab_4)
        self.label_pixsize4.setGeometry(QtCore.QRect(290, 100, 100, 32))
        self.label_pixsize4.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_pixsize4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_pixsize4.setObjectName("label_pixsize4")
        self.spinBox_pixsize4 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_pixsize4.setGeometry(QtCore.QRect(400, 100, 160, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_pixsize4.sizePolicy().hasHeightForWidth())
        self.spinBox_pixsize4.setSizePolicy(sizePolicy)
        self.spinBox_pixsize4.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_pixsize4.setFont(font)
        self.spinBox_pixsize4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_pixsize4.setFrame(True)
        self.spinBox_pixsize4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_pixsize4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_pixsize4.setKeyboardTracking(True)
        self.spinBox_pixsize4.setProperty("showGroupSeparator", False)
        self.spinBox_pixsize4.setMinimum(1)
        self.spinBox_pixsize4.setMaximum(200)
        self.spinBox_pixsize4.setProperty("value", 20)
        self.spinBox_pixsize4.setObjectName("spinBox_pixsize4")
        self.label_max_bbbv4 = QtWidgets.QLabel(self.tab_4)
        self.label_max_bbbv4.setGeometry(QtCore.QRect(290, 150, 100, 32))
        self.label_max_bbbv4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_max_bbbv4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_max_bbbv4.setObjectName("label_max_bbbv4")
        self.spinBox_max_bbbv4 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_max_bbbv4.setGeometry(QtCore.QRect(400, 150, 160, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_max_bbbv4.sizePolicy().hasHeightForWidth())
        self.spinBox_max_bbbv4.setSizePolicy(sizePolicy)
        self.spinBox_max_bbbv4.setMinimumSize(QtCore.QSize(124, 0))
        self.spinBox_max_bbbv4.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_max_bbbv4.setFont(font)
        self.spinBox_max_bbbv4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_max_bbbv4.setFrame(True)
        self.spinBox_max_bbbv4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_max_bbbv4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_max_bbbv4.setKeyboardTracking(True)
        self.spinBox_max_bbbv4.setProperty("showGroupSeparator", False)
        self.spinBox_max_bbbv4.setMaximum(9999)
        self.spinBox_max_bbbv4.setProperty("value", 9999)
        self.spinBox_max_bbbv4.setObjectName("spinBox_max_bbbv4")
        self.label_min_bbbv4 = QtWidgets.QLabel(self.tab_4)
        self.label_min_bbbv4.setGeometry(QtCore.QRect(290, 200, 101, 32))
        self.label_min_bbbv4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_min_bbbv4.setObjectName("label_min_bbbv4")
        self.spinBox_min_bbbv4 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_min_bbbv4.setGeometry(QtCore.QRect(400, 200, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_min_bbbv4.setFont(font)
        self.spinBox_min_bbbv4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_min_bbbv4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_min_bbbv4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_min_bbbv4.setKeyboardTracking(True)
        self.spinBox_min_bbbv4.setProperty("showGroupSeparator", False)
        self.spinBox_min_bbbv4.setMaximum(9999)
        self.spinBox_min_bbbv4.setProperty("value", 0)
        self.spinBox_min_bbbv4.setObjectName("spinBox_min_bbbv4")
        self.label_gamemode4 = QtWidgets.QLabel(self.tab_4)
        self.label_gamemode4.setGeometry(QtCore.QRect(20, 28, 61, 39))
        self.label_gamemode4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_gamemode4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_gamemode4.setObjectName("label_gamemode4")
        self.comboBox_gamemode4 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_gamemode4.setGeometry(QtCore.QRect(90, 30, 152, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_gamemode4.setFont(font)
        self.comboBox_gamemode4.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"width:120px;\n"
"height: 32px;\n"
"color: #3d3d3d;\n"
"\n"
"")
        self.comboBox_gamemode4.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_gamemode4.setObjectName("comboBox_gamemode4")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.comboBox_gamemode4.addItem("")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_minenum5 = QtWidgets.QLabel(self.tab_3)
        self.label_minenum5.setGeometry(QtCore.QRect(20, 200, 112, 32))
        self.label_minenum5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_minenum5.setObjectName("label_minenum5")
        self.spinBox_min_bbbv5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_min_bbbv5.setGeometry(QtCore.QRect(400, 200, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_min_bbbv5.setFont(font)
        self.spinBox_min_bbbv5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_min_bbbv5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_min_bbbv5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_min_bbbv5.setKeyboardTracking(True)
        self.spinBox_min_bbbv5.setProperty("showGroupSeparator", False)
        self.spinBox_min_bbbv5.setMaximum(9999)
        self.spinBox_min_bbbv5.setProperty("value", 0)
        self.spinBox_min_bbbv5.setObjectName("spinBox_min_bbbv5")
        self.label_height5 = QtWidgets.QLabel(self.tab_3)
        self.label_height5.setGeometry(QtCore.QRect(20, 100, 112, 32))
        self.label_height5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_height5.setObjectName("label_height5")
        self.spinBox_minenum5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_minenum5.setGeometry(QtCore.QRect(90, 200, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_minenum5.setFont(font)
        self.spinBox_minenum5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_minenum5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_minenum5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_minenum5.setKeyboardTracking(True)
        self.spinBox_minenum5.setProperty("showGroupSeparator", False)
        self.spinBox_minenum5.setMaximum(999)
        self.spinBox_minenum5.setProperty("value", 120)
        self.spinBox_minenum5.setObjectName("spinBox_minenum5")
        self.spinBox_width5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_width5.setGeometry(QtCore.QRect(90, 150, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_width5.setFont(font)
        self.spinBox_width5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_width5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_width5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_width5.setKeyboardTracking(True)
        self.spinBox_width5.setProperty("showGroupSeparator", False)
        self.spinBox_width5.setMaximum(999)
        self.spinBox_width5.setProperty("value", 30)
        self.spinBox_width5.setObjectName("spinBox_width5")
        self.label_max_bbbv5 = QtWidgets.QLabel(self.tab_3)
        self.label_max_bbbv5.setGeometry(QtCore.QRect(290, 150, 100, 32))
        self.label_max_bbbv5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_max_bbbv5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_max_bbbv5.setObjectName("label_max_bbbv5")
        self.spinBox_max_bbbv5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_max_bbbv5.setGeometry(QtCore.QRect(400, 150, 160, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_max_bbbv5.sizePolicy().hasHeightForWidth())
        self.spinBox_max_bbbv5.setSizePolicy(sizePolicy)
        self.spinBox_max_bbbv5.setMinimumSize(QtCore.QSize(124, 0))
        self.spinBox_max_bbbv5.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_max_bbbv5.setFont(font)
        self.spinBox_max_bbbv5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_max_bbbv5.setFrame(True)
        self.spinBox_max_bbbv5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_max_bbbv5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_max_bbbv5.setKeyboardTracking(True)
        self.spinBox_max_bbbv5.setProperty("showGroupSeparator", False)
        self.spinBox_max_bbbv5.setMaximum(9999)
        self.spinBox_max_bbbv5.setProperty("value", 9999)
        self.spinBox_max_bbbv5.setObjectName("spinBox_max_bbbv5")
        self.label_min_bbbv5 = QtWidgets.QLabel(self.tab_3)
        self.label_min_bbbv5.setGeometry(QtCore.QRect(290, 200, 101, 32))
        self.label_min_bbbv5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_min_bbbv5.setObjectName("label_min_bbbv5")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 30, 152, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"width:120px;\n"
"height: 32px;\n"
"color: #3d3d3d;\n"
"\n"
"")
        self.comboBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_pixsize5 = QtWidgets.QLabel(self.tab_3)
        self.label_pixsize5.setGeometry(QtCore.QRect(290, 100, 100, 32))
        self.label_pixsize5.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_pixsize5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_pixsize5.setObjectName("label_pixsize5")
        self.label_width5 = QtWidgets.QLabel(self.tab_3)
        self.label_width5.setGeometry(QtCore.QRect(20, 150, 112, 32))
        self.label_width5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_width5.setObjectName("label_width5")
        self.spinBox_pixsize5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_pixsize5.setGeometry(QtCore.QRect(400, 100, 160, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_pixsize5.sizePolicy().hasHeightForWidth())
        self.spinBox_pixsize5.setSizePolicy(sizePolicy)
        self.spinBox_pixsize5.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_pixsize5.setFont(font)
        self.spinBox_pixsize5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_pixsize5.setFrame(True)
        self.spinBox_pixsize5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_pixsize5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_pixsize5.setKeyboardTracking(True)
        self.spinBox_pixsize5.setProperty("showGroupSeparator", False)
        self.spinBox_pixsize5.setMinimum(1)
        self.spinBox_pixsize5.setMaximum(200)
        self.spinBox_pixsize5.setProperty("value", 20)
        self.spinBox_pixsize5.setObjectName("spinBox_pixsize5")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(20, 28, 61, 39))
        self.label_25.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_25.setObjectName("label_25")
        self.spinBox_height5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_height5.setGeometry(QtCore.QRect(90, 100, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_height5.setFont(font)
        self.spinBox_height5.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_height5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_height5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_height5.setKeyboardTracking(True)
        self.spinBox_height5.setProperty("showGroupSeparator", False)
        self.spinBox_height5.setMaximum(999)
        self.spinBox_height5.setProperty("value", 16)
        self.spinBox_height5.setObjectName("spinBox_height5")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_41 = QtWidgets.QWidget()
        self.tab_41.setObjectName("tab_41")
        self.spinBox_height6 = QtWidgets.QSpinBox(self.tab_41)
        self.spinBox_height6.setGeometry(QtCore.QRect(90, 100, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_height6.setFont(font)
        self.spinBox_height6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_height6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_height6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_height6.setKeyboardTracking(True)
        self.spinBox_height6.setProperty("showGroupSeparator", False)
        self.spinBox_height6.setMaximum(999)
        self.spinBox_height6.setProperty("value", 24)
        self.spinBox_height6.setObjectName("spinBox_height6")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_41)
        self.comboBox_3.setGeometry(QtCore.QRect(90, 30, 152, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"width:120px;\n"
"height: 32px;\n"
"color: #3d3d3d;\n"
"\n"
"")
        self.comboBox_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_width6 = QtWidgets.QLabel(self.tab_41)
        self.label_width6.setGeometry(QtCore.QRect(20, 150, 112, 32))
        self.label_width6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_width6.setObjectName("label_width6")
        self.spinBox_pixsize6 = QtWidgets.QSpinBox(self.tab_41)
        self.spinBox_pixsize6.setGeometry(QtCore.QRect(400, 100, 160, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_pixsize6.sizePolicy().hasHeightForWidth())
        self.spinBox_pixsize6.setSizePolicy(sizePolicy)
        self.spinBox_pixsize6.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_pixsize6.setFont(font)
        self.spinBox_pixsize6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_pixsize6.setFrame(True)
        self.spinBox_pixsize6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_pixsize6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_pixsize6.setKeyboardTracking(True)
        self.spinBox_pixsize6.setProperty("showGroupSeparator", False)
        self.spinBox_pixsize6.setMinimum(1)
        self.spinBox_pixsize6.setMaximum(200)
        self.spinBox_pixsize6.setProperty("value", 20)
        self.spinBox_pixsize6.setObjectName("spinBox_pixsize6")
        self.label_minenum6 = QtWidgets.QLabel(self.tab_41)
        self.label_minenum6.setGeometry(QtCore.QRect(20, 200, 112, 32))
        self.label_minenum6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_minenum6.setObjectName("label_minenum6")
        self.spinBox_width6 = QtWidgets.QSpinBox(self.tab_41)
        self.spinBox_width6.setGeometry(QtCore.QRect(90, 150, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_width6.setFont(font)
        self.spinBox_width6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_width6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_width6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_width6.setKeyboardTracking(True)
        self.spinBox_width6.setProperty("showGroupSeparator", False)
        self.spinBox_width6.setMaximum(999)
        self.spinBox_width6.setProperty("value", 36)
        self.spinBox_width6.setObjectName("spinBox_width6")
        self.label_28 = QtWidgets.QLabel(self.tab_41)
        self.label_28.setGeometry(QtCore.QRect(20, 28, 61, 39))
        self.label_28.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_28.setObjectName("label_28")
        self.spinBox_min_bbbv6 = QtWidgets.QSpinBox(self.tab_41)
        self.spinBox_min_bbbv6.setGeometry(QtCore.QRect(400, 200, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_min_bbbv6.setFont(font)
        self.spinBox_min_bbbv6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_min_bbbv6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_min_bbbv6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_min_bbbv6.setKeyboardTracking(True)
        self.spinBox_min_bbbv6.setProperty("showGroupSeparator", False)
        self.spinBox_min_bbbv6.setMaximum(9999)
        self.spinBox_min_bbbv6.setProperty("value", 0)
        self.spinBox_min_bbbv6.setObjectName("spinBox_min_bbbv6")
        self.label_pixsize6 = QtWidgets.QLabel(self.tab_41)
        self.label_pixsize6.setGeometry(QtCore.QRect(290, 100, 100, 32))
        self.label_pixsize6.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_pixsize6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_pixsize6.setObjectName("label_pixsize6")
        self.label_min_bbbv6 = QtWidgets.QLabel(self.tab_41)
        self.label_min_bbbv6.setGeometry(QtCore.QRect(290, 200, 101, 32))
        self.label_min_bbbv6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_min_bbbv6.setObjectName("label_min_bbbv6")
        self.spinBox_max_bbbv6 = QtWidgets.QSpinBox(self.tab_41)
        self.spinBox_max_bbbv6.setGeometry(QtCore.QRect(400, 150, 160, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_max_bbbv6.sizePolicy().hasHeightForWidth())
        self.spinBox_max_bbbv6.setSizePolicy(sizePolicy)
        self.spinBox_max_bbbv6.setMinimumSize(QtCore.QSize(124, 0))
        self.spinBox_max_bbbv6.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_max_bbbv6.setFont(font)
        self.spinBox_max_bbbv6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_max_bbbv6.setFrame(True)
        self.spinBox_max_bbbv6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_max_bbbv6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_max_bbbv6.setKeyboardTracking(True)
        self.spinBox_max_bbbv6.setProperty("showGroupSeparator", False)
        self.spinBox_max_bbbv6.setMaximum(9999)
        self.spinBox_max_bbbv6.setProperty("value", 9999)
        self.spinBox_max_bbbv6.setObjectName("spinBox_max_bbbv6")
        self.label_height6 = QtWidgets.QLabel(self.tab_41)
        self.label_height6.setGeometry(QtCore.QRect(20, 100, 112, 32))
        self.label_height6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_height6.setObjectName("label_height6")
        self.label_max_bbbv6 = QtWidgets.QLabel(self.tab_41)
        self.label_max_bbbv6.setGeometry(QtCore.QRect(290, 150, 100, 32))
        self.label_max_bbbv6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_max_bbbv6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_max_bbbv6.setObjectName("label_max_bbbv6")
        self.spinBox_minenum6 = QtWidgets.QSpinBox(self.tab_41)
        self.spinBox_minenum6.setGeometry(QtCore.QRect(90, 200, 160, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_minenum6.setFont(font)
        self.spinBox_minenum6.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_minenum6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_minenum6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_minenum6.setKeyboardTracking(True)
        self.spinBox_minenum6.setProperty("showGroupSeparator", False)
        self.spinBox_minenum6.setMaximum(999)
        self.spinBox_minenum6.setProperty("value", 200)
        self.spinBox_minenum6.setObjectName("spinBox_minenum6")
        self.tabWidget.addTab(self.tab_41, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_gamemode4.setCurrentIndex(4)
        self.comboBox_2.setCurrentIndex(4)
        self.comboBox_3.setCurrentIndex(4)
        self.pushButton_2.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "快捷键设置"))
        self.pushButton_2.setText(_translate("Form", "取消"))
        self.pushButton.setText(_translate("Form", "确定"))
        self.label_height4.setText(_translate("Form", "高度："))
        self.label_width4.setText(_translate("Form", "宽度："))
        self.label_minenum4.setText(_translate("Form", "雷数："))
        self.label_pixsize4.setText(_translate("Form", "方块边长："))
        self.label_max_bbbv4.setText(_translate("Form", "最大3BV："))
        self.label_min_bbbv4.setText(_translate("Form", "最小3BV："))
        self.label_gamemode4.setText(_translate("Form", "模式："))
        self.comboBox_gamemode4.setItemText(0, _translate("Form", "标准"))
        self.comboBox_gamemode4.setItemText(1, _translate("Form", "Win7"))
        self.comboBox_gamemode4.setItemText(2, _translate("Form", "强无猜"))
        self.comboBox_gamemode4.setItemText(3, _translate("Form", "弱无猜"))
        self.comboBox_gamemode4.setItemText(4, _translate("Form", "竞速无猜"))
        self.comboBox_gamemode4.setItemText(5, _translate("Form", "准无猜"))
        self.comboBox_gamemode4.setItemText(6, _translate("Form", "强可猜"))
        self.comboBox_gamemode4.setItemText(7, _translate("Form", "弱可猜"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "快捷键[4]"))
        self.label_minenum5.setText(_translate("Form", "雷数："))
        self.label_height5.setText(_translate("Form", "高度："))
        self.label_max_bbbv5.setText(_translate("Form", "最大3BV："))
        self.label_min_bbbv5.setText(_translate("Form", "最小3BV："))
        self.comboBox_2.setItemText(0, _translate("Form", "标准"))
        self.comboBox_2.setItemText(1, _translate("Form", "Win7"))
        self.comboBox_2.setItemText(2, _translate("Form", "强无猜"))
        self.comboBox_2.setItemText(3, _translate("Form", "弱无猜"))
        self.comboBox_2.setItemText(4, _translate("Form", "竞速无猜"))
        self.comboBox_2.setItemText(5, _translate("Form", "准无猜"))
        self.comboBox_2.setItemText(6, _translate("Form", "强可猜"))
        self.comboBox_2.setItemText(7, _translate("Form", "弱可猜"))
        self.label_pixsize5.setText(_translate("Form", "方块边长："))
        self.label_width5.setText(_translate("Form", "宽度："))
        self.label_25.setText(_translate("Form", "模式："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "快捷键[5]"))
        self.comboBox_3.setItemText(0, _translate("Form", "标准"))
        self.comboBox_3.setItemText(1, _translate("Form", "Win7"))
        self.comboBox_3.setItemText(2, _translate("Form", "强无猜"))
        self.comboBox_3.setItemText(3, _translate("Form", "弱无猜"))
        self.comboBox_3.setItemText(4, _translate("Form", "竞速无猜"))
        self.comboBox_3.setItemText(5, _translate("Form", "准无猜"))
        self.comboBox_3.setItemText(6, _translate("Form", "强可猜"))
        self.comboBox_3.setItemText(7, _translate("Form", "弱可猜"))
        self.label_width6.setText(_translate("Form", "宽度："))
        self.label_minenum6.setText(_translate("Form", "雷数："))
        self.label_28.setText(_translate("Form", "模式："))
        self.label_pixsize6.setText(_translate("Form", "方块边长："))
        self.label_min_bbbv6.setText(_translate("Form", "最小3BV："))
        self.label_height6.setText(_translate("Form", "高度："))
        self.label_max_bbbv6.setText(_translate("Form", "最大3BV："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_41), _translate("Form", "快捷键[6]"))
