# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gs_shortcuts.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(620, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(620, 440))
        Form.setMaximumSize(QtCore.QSize(620, 440))
        Form.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/cat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 380, 251, 41))
        self.pushButton_2.setStyleSheet("border-image: url(media/button.png);\n"
"font: 16pt \"黑体\";\n"
"color:white;font: bold;")
        self.pushButton_2.setShortcut("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 380, 251, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setStyleSheet("border-image: url(media/button.png);\n"
"font: 16pt \"黑体\";\n"
"color:white;font: bold;")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 30, 581, 331))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 201, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setGeometry(QtCore.QRect(21, 83, 232, 155))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_8.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(124, 0))
        self.spinBox.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setFrame(True)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setKeyboardTracking(True)
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setMaximum(9999)
        self.spinBox.setProperty("value", 9999)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_2.setKeyboardTracking(True)
        self.spinBox_2.setProperty("showGroupSeparator", False)
        self.spinBox_2.setMaximum(9999)
        self.spinBox_2.setProperty("value", 0)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_3.setKeyboardTracking(True)
        self.spinBox_3.setProperty("showGroupSeparator", False)
        self.spinBox_3.setMaximum(999)
        self.spinBox_3.setProperty("value", 16)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_4.setKeyboardTracking(True)
        self.spinBox_4.setProperty("showGroupSeparator", False)
        self.spinBox_4.setMaximum(999)
        self.spinBox_4.setProperty("value", 16)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 3, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.tab_4)
        self.widget1.setGeometry(QtCore.QRect(280, 83, 273, 155))
        self.widget1.setObjectName("widget1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_14 = QtWidgets.QLabel(self.widget1)
        self.label_14.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_14.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_6.sizePolicy().hasHeightForWidth())
        self.spinBox_6.setSizePolicy(sizePolicy)
        self.spinBox_6.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_6.setFont(font)
        self.spinBox_6.setFrame(True)
        self.spinBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_6.setKeyboardTracking(True)
        self.spinBox_6.setProperty("showGroupSeparator", False)
        self.spinBox_6.setMinimum(1)
        self.spinBox_6.setMaximum(200)
        self.spinBox_6.setProperty("value", 20)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_7.addWidget(self.spinBox_6, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget1)
        self.label_15.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 1, 0, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_7.sizePolicy().hasHeightForWidth())
        self.spinBox_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_7.setFont(font)
        self.spinBox_7.setFrame(True)
        self.spinBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_7.setKeyboardTracking(True)
        self.spinBox_7.setProperty("showGroupSeparator", False)
        self.spinBox_7.setMaximum(99999999)
        self.spinBox_7.setProperty("value", 100000)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_7.addWidget(self.spinBox_7, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget1)
        self.label_16.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 2, 0, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_8.sizePolicy().hasHeightForWidth())
        self.spinBox_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_8.setFont(font)
        self.spinBox_8.setFrame(True)
        self.spinBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_8.setKeyboardTracking(True)
        self.spinBox_8.setProperty("showGroupSeparator", False)
        self.spinBox_8.setMaximum(999)
        self.spinBox_8.setProperty("value", 30)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout_7.addWidget(self.spinBox_8, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget1)
        self.label_13.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 3, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_5.setKeyboardTracking(True)
        self.spinBox_5.setProperty("showGroupSeparator", False)
        self.spinBox_5.setMaximum(999)
        self.spinBox_5.setProperty("value", 72)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_7.addWidget(self.spinBox_5, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_6.setGeometry(QtCore.QRect(30, 30, 201, 41))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_25.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(21, 83, 232, 155))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_21.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_21.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_13.sizePolicy().hasHeightForWidth())
        self.spinBox_13.setSizePolicy(sizePolicy)
        self.spinBox_13.setMinimumSize(QtCore.QSize(124, 0))
        self.spinBox_13.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_13.setFont(font)
        self.spinBox_13.setFrame(True)
        self.spinBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_13.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_13.setKeyboardTracking(True)
        self.spinBox_13.setProperty("showGroupSeparator", False)
        self.spinBox_13.setMaximum(9999)
        self.spinBox_13.setProperty("value", 9999)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout_3.addWidget(self.spinBox_13, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_22.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 1, 0, 1, 1)
        self.spinBox_14 = QtWidgets.QSpinBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_14.setFont(font)
        self.spinBox_14.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_14.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_14.setKeyboardTracking(True)
        self.spinBox_14.setProperty("showGroupSeparator", False)
        self.spinBox_14.setMaximum(9999)
        self.spinBox_14.setProperty("value", 0)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridLayout_3.addWidget(self.spinBox_14, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_23.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 2, 0, 1, 1)
        self.spinBox_15 = QtWidgets.QSpinBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_15.setFont(font)
        self.spinBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_15.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_15.setKeyboardTracking(True)
        self.spinBox_15.setProperty("showGroupSeparator", False)
        self.spinBox_15.setMaximum(999)
        self.spinBox_15.setProperty("value", 16)
        self.spinBox_15.setObjectName("spinBox_15")
        self.gridLayout_3.addWidget(self.spinBox_15, 2, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_24.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 3, 0, 1, 1)
        self.spinBox_16 = QtWidgets.QSpinBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_16.setFont(font)
        self.spinBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_16.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_16.setKeyboardTracking(True)
        self.spinBox_16.setProperty("showGroupSeparator", False)
        self.spinBox_16.setMaximum(999)
        self.spinBox_16.setProperty("value", 30)
        self.spinBox_16.setObjectName("spinBox_16")
        self.gridLayout_3.addWidget(self.spinBox_16, 3, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(280, 83, 273, 155))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_17.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 0, 0, 1, 1)
        self.spinBox_9 = QtWidgets.QSpinBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_9.sizePolicy().hasHeightForWidth())
        self.spinBox_9.setSizePolicy(sizePolicy)
        self.spinBox_9.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_9.setFont(font)
        self.spinBox_9.setFrame(True)
        self.spinBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_9.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_9.setKeyboardTracking(True)
        self.spinBox_9.setProperty("showGroupSeparator", False)
        self.spinBox_9.setMinimum(1)
        self.spinBox_9.setMaximum(200)
        self.spinBox_9.setProperty("value", 20)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout_8.addWidget(self.spinBox_9, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 1, 0, 1, 1)
        self.spinBox_10 = QtWidgets.QSpinBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_10.sizePolicy().hasHeightForWidth())
        self.spinBox_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_10.setFont(font)
        self.spinBox_10.setFrame(True)
        self.spinBox_10.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_10.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_10.setKeyboardTracking(True)
        self.spinBox_10.setProperty("showGroupSeparator", False)
        self.spinBox_10.setMaximum(99999999)
        self.spinBox_10.setProperty("value", 100000)
        self.spinBox_10.setObjectName("spinBox_10")
        self.gridLayout_8.addWidget(self.spinBox_10, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_19.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 2, 0, 1, 1)
        self.spinBox_11 = QtWidgets.QSpinBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_11.sizePolicy().hasHeightForWidth())
        self.spinBox_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_11.setFont(font)
        self.spinBox_11.setFrame(True)
        self.spinBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_11.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_11.setKeyboardTracking(True)
        self.spinBox_11.setProperty("showGroupSeparator", False)
        self.spinBox_11.setMaximum(999)
        self.spinBox_11.setProperty("value", 30)
        self.spinBox_11.setObjectName("spinBox_11")
        self.gridLayout_8.addWidget(self.spinBox_11, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_20.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 3, 0, 1, 1)
        self.spinBox_12 = QtWidgets.QSpinBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_12.setFont(font)
        self.spinBox_12.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_12.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_12.setKeyboardTracking(True)
        self.spinBox_12.setProperty("showGroupSeparator", False)
        self.spinBox_12.setMaximum(999)
        self.spinBox_12.setProperty("value", 120)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout_8.addWidget(self.spinBox_12, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_41 = QtWidgets.QWidget()
        self.tab_41.setObjectName("tab_41")
        self.layoutWidget_7 = QtWidgets.QWidget(self.tab_41)
        self.layoutWidget_7.setGeometry(QtCore.QRect(30, 30, 201, 41))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_7)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_34.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 0, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_41)
        self.layoutWidget_3.setGeometry(QtCore.QRect(280, 83, 273, 155))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_26.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_26.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_26.setObjectName("label_26")
        self.gridLayout_9.addWidget(self.label_26, 0, 0, 1, 1)
        self.spinBox_17 = QtWidgets.QSpinBox(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_17.sizePolicy().hasHeightForWidth())
        self.spinBox_17.setSizePolicy(sizePolicy)
        self.spinBox_17.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_17.setFont(font)
        self.spinBox_17.setFrame(True)
        self.spinBox_17.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_17.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_17.setKeyboardTracking(True)
        self.spinBox_17.setProperty("showGroupSeparator", False)
        self.spinBox_17.setMinimum(1)
        self.spinBox_17.setMaximum(200)
        self.spinBox_17.setProperty("value", 20)
        self.spinBox_17.setObjectName("spinBox_17")
        self.gridLayout_9.addWidget(self.spinBox_17, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_27.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 1, 0, 1, 1)
        self.spinBox_18 = QtWidgets.QSpinBox(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_18.sizePolicy().hasHeightForWidth())
        self.spinBox_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_18.setFont(font)
        self.spinBox_18.setFrame(True)
        self.spinBox_18.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_18.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_18.setKeyboardTracking(True)
        self.spinBox_18.setProperty("showGroupSeparator", False)
        self.spinBox_18.setMaximum(99999999)
        self.spinBox_18.setProperty("value", 100000)
        self.spinBox_18.setObjectName("spinBox_18")
        self.gridLayout_9.addWidget(self.spinBox_18, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_28.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 2, 0, 1, 1)
        self.spinBox_19 = QtWidgets.QSpinBox(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_19.sizePolicy().hasHeightForWidth())
        self.spinBox_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_19.setFont(font)
        self.spinBox_19.setFrame(True)
        self.spinBox_19.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_19.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_19.setKeyboardTracking(True)
        self.spinBox_19.setProperty("showGroupSeparator", False)
        self.spinBox_19.setMaximum(999)
        self.spinBox_19.setProperty("value", 30)
        self.spinBox_19.setObjectName("spinBox_19")
        self.gridLayout_9.addWidget(self.spinBox_19, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_29.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_29.setObjectName("label_29")
        self.gridLayout_9.addWidget(self.label_29, 3, 0, 1, 1)
        self.spinBox_20 = QtWidgets.QSpinBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_20.setFont(font)
        self.spinBox_20.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_20.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_20.setKeyboardTracking(True)
        self.spinBox_20.setProperty("showGroupSeparator", False)
        self.spinBox_20.setMaximum(999)
        self.spinBox_20.setProperty("value", 200)
        self.spinBox_20.setObjectName("spinBox_20")
        self.gridLayout_9.addWidget(self.spinBox_20, 3, 1, 1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_41)
        self.layoutWidget_4.setGeometry(QtCore.QRect(21, 83, 232, 155))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_30.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_30.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 0, 0, 1, 1)
        self.spinBox_21 = QtWidgets.QSpinBox(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_21.sizePolicy().hasHeightForWidth())
        self.spinBox_21.setSizePolicy(sizePolicy)
        self.spinBox_21.setMinimumSize(QtCore.QSize(124, 0))
        self.spinBox_21.setMaximumSize(QtCore.QSize(99999, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_21.setFont(font)
        self.spinBox_21.setFrame(True)
        self.spinBox_21.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_21.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_21.setKeyboardTracking(True)
        self.spinBox_21.setProperty("showGroupSeparator", False)
        self.spinBox_21.setMaximum(9999)
        self.spinBox_21.setProperty("value", 9999)
        self.spinBox_21.setObjectName("spinBox_21")
        self.gridLayout_5.addWidget(self.spinBox_21, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_31.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 1, 0, 1, 1)
        self.spinBox_22 = QtWidgets.QSpinBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_22.setFont(font)
        self.spinBox_22.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_22.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_22.setKeyboardTracking(True)
        self.spinBox_22.setProperty("showGroupSeparator", False)
        self.spinBox_22.setMaximum(9999)
        self.spinBox_22.setProperty("value", 0)
        self.spinBox_22.setObjectName("spinBox_22")
        self.gridLayout_5.addWidget(self.spinBox_22, 1, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_32.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 2, 0, 1, 1)
        self.spinBox_23 = QtWidgets.QSpinBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_23.setFont(font)
        self.spinBox_23.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_23.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_23.setKeyboardTracking(True)
        self.spinBox_23.setProperty("showGroupSeparator", False)
        self.spinBox_23.setMaximum(999)
        self.spinBox_23.setProperty("value", 24)
        self.spinBox_23.setObjectName("spinBox_23")
        self.gridLayout_5.addWidget(self.spinBox_23, 2, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_33.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 3, 0, 1, 1)
        self.spinBox_24 = QtWidgets.QSpinBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_24.setFont(font)
        self.spinBox_24.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_24.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_24.setKeyboardTracking(True)
        self.spinBox_24.setProperty("showGroupSeparator", False)
        self.spinBox_24.setMaximum(999)
        self.spinBox_24.setProperty("value", 36)
        self.spinBox_24.setObjectName("spinBox_24")
        self.gridLayout_5.addWidget(self.spinBox_24, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_41, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(4)
        self.comboBox_2.setCurrentIndex(4)
        self.comboBox_3.setCurrentIndex(4)
        self.pushButton_2.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "快捷键设置"))
        self.pushButton_2.setText(_translate("Form", "取消"))
        self.pushButton.setText(_translate("Form", "确定"))
        self.label_9.setText(_translate("Form", "模式："))
        self.comboBox.setItemText(0, _translate("Form", "标准"))
        self.comboBox.setItemText(1, _translate("Form", "Win7"))
        self.comboBox.setItemText(2, _translate("Form", "强无猜"))
        self.comboBox.setItemText(3, _translate("Form", "弱无猜"))
        self.comboBox.setItemText(4, _translate("Form", "竞速无猜"))
        self.comboBox.setItemText(5, _translate("Form", "准无猜"))
        self.comboBox.setItemText(6, _translate("Form", "强可猜"))
        self.comboBox.setItemText(7, _translate("Form", "弱可猜"))
        self.label_8.setText(_translate("Form", "最大3BV："))
        self.label_10.setText(_translate("Form", "最小3BV："))
        self.label_11.setText(_translate("Form", "高度："))
        self.label_12.setText(_translate("Form", "宽度："))
        self.label_14.setText(_translate("Form", "方块边长："))
        self.label_15.setText(_translate("Form", "最大尝试次数："))
        self.label_16.setText(_translate("Form", "最大枚举次数："))
        self.label_13.setText(_translate("Form", "雷数："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "快捷键[4]"))
        self.label_25.setText(_translate("Form", "模式："))
        self.comboBox_2.setItemText(0, _translate("Form", "标准"))
        self.comboBox_2.setItemText(1, _translate("Form", "Win7"))
        self.comboBox_2.setItemText(2, _translate("Form", "强无猜"))
        self.comboBox_2.setItemText(3, _translate("Form", "弱无猜"))
        self.comboBox_2.setItemText(4, _translate("Form", "竞速无猜"))
        self.comboBox_2.setItemText(5, _translate("Form", "准无猜"))
        self.comboBox_2.setItemText(6, _translate("Form", "强可猜"))
        self.comboBox_2.setItemText(7, _translate("Form", "弱可猜"))
        self.label_21.setText(_translate("Form", "最大3BV："))
        self.label_22.setText(_translate("Form", "最小3BV："))
        self.label_23.setText(_translate("Form", "高度："))
        self.label_24.setText(_translate("Form", "宽度："))
        self.label_17.setText(_translate("Form", "方块边长："))
        self.label_18.setText(_translate("Form", "最大尝试次数："))
        self.label_19.setText(_translate("Form", "最大枚举次数："))
        self.label_20.setText(_translate("Form", "雷数："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "快捷键[5]"))
        self.label_34.setText(_translate("Form", "模式："))
        self.comboBox_3.setItemText(0, _translate("Form", "标准"))
        self.comboBox_3.setItemText(1, _translate("Form", "Win7"))
        self.comboBox_3.setItemText(2, _translate("Form", "强无猜"))
        self.comboBox_3.setItemText(3, _translate("Form", "弱无猜"))
        self.comboBox_3.setItemText(4, _translate("Form", "竞速无猜"))
        self.comboBox_3.setItemText(5, _translate("Form", "准无猜"))
        self.comboBox_3.setItemText(6, _translate("Form", "强可猜"))
        self.comboBox_3.setItemText(7, _translate("Form", "弱可猜"))
        self.label_26.setText(_translate("Form", "方块边长："))
        self.label_27.setText(_translate("Form", "最大尝试次数："))
        self.label_28.setText(_translate("Form", "最大枚举次数："))
        self.label_29.setText(_translate("Form", "雷数："))
        self.label_30.setText(_translate("Form", "最大3BV："))
        self.label_31.setText(_translate("Form", "最小3BV："))
        self.label_32.setText(_translate("Form", "高度："))
        self.label_33.setText(_translate("Form", "宽度："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_41), _translate("Form", "快捷键[6]"))

