# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gs.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(560, 520)
        Form.setMinimumSize(QtCore.QSize(560, 520))
        Form.setMaximumSize(QtCore.QSize(560, 520))
        Form.setMouseTracking(True)
        Form.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/cat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QComboBox::drop-down {\n"
"    width: 26px;\n"
"}")
        self.pushButton_yes = QtWidgets.QPushButton(Form)
        self.pushButton_yes.setGeometry(QtCore.QRect(30, 460, 241, 38))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_yes.setFont(font)
        self.pushButton_yes.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_yes.setStyleSheet("border-image: url(media/button.png);\n"
"font: 16pt \"黑体\";\n"
"color:white;font: bold;")
        self.pushButton_yes.setAutoDefault(False)
        self.pushButton_yes.setFlat(False)
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.pushButton_no = QtWidgets.QPushButton(Form)
        self.pushButton_no.setGeometry(QtCore.QRect(290, 460, 241, 38))
        self.pushButton_no.setStyleSheet("border-image: url(media/button.png);\n"
"font: 16pt \"黑体\";\n"
"color:white;font: bold;")
        self.pushButton_no.setObjectName("pushButton_no")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(30, 440, 501, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalSlider_transparency = QtWidgets.QSlider(Form)
        self.horizontalSlider_transparency.setGeometry(QtCore.QRect(150, 415, 311, 22))
        self.horizontalSlider_transparency.setMaximum(100)
        self.horizontalSlider_transparency.setSingleStep(1)
        self.horizontalSlider_transparency.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_transparency.setObjectName("horizontalSlider_transparency")
        self.label_transparency = QtWidgets.QLabel(Form)
        self.label_transparency.setGeometry(QtCore.QRect(40, 410, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_transparency.setFont(font)
        self.label_transparency.setScaledContents(False)
        self.label_transparency.setWordWrap(False)
        self.label_transparency.setObjectName("label_transparency")
        self.label_transparency_percent_value = QtWidgets.QLabel(Form)
        self.label_transparency_percent_value.setGeometry(QtCore.QRect(465, 410, 41, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_transparency_percent_value.setFont(font)
        self.label_transparency_percent_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_transparency_percent_value.setText("")
        self.label_transparency_percent_value.setScaledContents(False)
        self.label_transparency_percent_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_transparency_percent_value.setWordWrap(False)
        self.label_transparency_percent_value.setObjectName("label_transparency_percent_value")
        self.label_transparency_percent = QtWidgets.QLabel(Form)
        self.label_transparency_percent.setGeometry(QtCore.QRect(510, 410, 21, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_transparency_percent.setFont(font)
        self.label_transparency_percent.setScaledContents(False)
        self.label_transparency_percent.setWordWrap(False)
        self.label_transparency_percent.setObjectName("label_transparency_percent")
        self.checkBox_end_then_flag = QtWidgets.QCheckBox(Form)
        self.checkBox_end_then_flag.setGeometry(QtCore.QRect(40, 260, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.checkBox_end_then_flag.setFont(font)
        self.checkBox_end_then_flag.setToolTip("")
        self.checkBox_end_then_flag.setStyleSheet("")
        self.checkBox_end_then_flag.setObjectName("checkBox_end_then_flag")
        self.label_label = QtWidgets.QLabel(Form)
        self.label_label.setGeometry(QtCore.QRect(30, 80, 61, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_label.setFont(font)
        self.label_label.setScaledContents(False)
        self.label_label.setWordWrap(False)
        self.label_label.setObjectName("label_label")
        self.label_race_label = QtWidgets.QLabel(Form)
        self.label_race_label.setGeometry(QtCore.QRect(30, 120, 91, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_race_label.setFont(font)
        self.label_race_label.setScaledContents(False)
        self.label_race_label.setWordWrap(False)
        self.label_race_label.setObjectName("label_race_label")
        self.checkBox_filter_forever = QtWidgets.QCheckBox(Form)
        self.checkBox_filter_forever.setGeometry(QtCore.QRect(40, 230, 311, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.checkBox_filter_forever.setFont(font)
        self.checkBox_filter_forever.setStyleSheet("")
        self.checkBox_filter_forever.setObjectName("checkBox_filter_forever")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(30, 60, 501, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_auto_replay_percent = QtWidgets.QLabel(Form)
        self.label_auto_replay_percent.setGeometry(QtCore.QRect(320, 292, 21, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_auto_replay_percent.setFont(font)
        self.label_auto_replay_percent.setScaledContents(False)
        self.label_auto_replay_percent.setWordWrap(False)
        self.label_auto_replay_percent.setObjectName("label_auto_replay_percent")
        self.checkBox_autosave_video = QtWidgets.QCheckBox(Form)
        self.checkBox_autosave_video.setGeometry(QtCore.QRect(40, 200, 311, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.checkBox_autosave_video.setFont(font)
        self.checkBox_autosave_video.setStyleSheet("")
        self.checkBox_autosave_video.setObjectName("checkBox_autosave_video")
        self.label_country = QtWidgets.QLabel(Form)
        self.label_country.setGeometry(QtCore.QRect(30, 160, 61, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_country.setFont(font)
        self.label_country.setScaledContents(False)
        self.label_country.setWordWrap(False)
        self.label_country.setObjectName("label_country")
        self.label_national_flag = QtWidgets.QLabel(Form)
        self.label_national_flag.setGeometry(QtCore.QRect(310, 160, 51, 31))
        self.label_national_flag.setStyleSheet("background-color:rgb(255, 42, 42)")
        self.label_national_flag.setText("")
        self.label_national_flag.setObjectName("label_national_flag")
        self.label_gamemode = QtWidgets.QLabel(Form)
        self.label_gamemode.setGeometry(QtCore.QRect(30, 20, 101, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_gamemode.setFont(font)
        self.label_gamemode.setScaledContents(False)
        self.label_gamemode.setWordWrap(False)
        self.label_gamemode.setObjectName("label_gamemode")
        self.lineEdit_race_label = QtWidgets.QLineEdit(Form)
        self.lineEdit_race_label.setGeometry(QtCore.QRect(130, 120, 401, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_race_label.setFont(font)
        self.lineEdit_race_label.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_race_label.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.lineEdit_race_label.setText("")
        self.lineEdit_race_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_race_label.setObjectName("lineEdit_race_label")
        self.lineEdit_label = QtWidgets.QLineEdit(Form)
        self.lineEdit_label.setGeometry(QtCore.QRect(130, 80, 401, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_label.setFont(font)
        self.lineEdit_label.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_label.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.lineEdit_label.setText("")
        self.lineEdit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_label.setObjectName("lineEdit_label")
        self.lineEdit_country = QtWidgets.QLineEdit(Form)
        self.lineEdit_country.setGeometry(QtCore.QRect(130, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_country.setFont(font)
        self.lineEdit_country.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_country.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.lineEdit_country.setText("")
        self.lineEdit_country.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_country.setObjectName("lineEdit_country")
        self.spinBox_max_bbbv = QtWidgets.QSpinBox(Form)
        self.spinBox_max_bbbv.setGeometry(QtCore.QRect(180, 382, 132, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_max_bbbv.sizePolicy().hasHeightForWidth())
        self.spinBox_max_bbbv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_max_bbbv.setFont(font)
        self.spinBox_max_bbbv.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_max_bbbv.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_max_bbbv.setFrame(True)
        self.spinBox_max_bbbv.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_max_bbbv.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_max_bbbv.setKeyboardTracking(True)
        self.spinBox_max_bbbv.setProperty("showGroupSeparator", False)
        self.spinBox_max_bbbv.setMinimum(0)
        self.spinBox_max_bbbv.setMaximum(9999)
        self.spinBox_max_bbbv.setProperty("value", 9999)
        self.spinBox_max_bbbv.setObjectName("spinBox_max_bbbv")
        self.spinBox_min_bbbv = QtWidgets.QSpinBox(Form)
        self.spinBox_min_bbbv.setGeometry(QtCore.QRect(180, 352, 132, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_min_bbbv.sizePolicy().hasHeightForWidth())
        self.spinBox_min_bbbv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_min_bbbv.setFont(font)
        self.spinBox_min_bbbv.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_min_bbbv.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_min_bbbv.setFrame(True)
        self.spinBox_min_bbbv.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_min_bbbv.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_min_bbbv.setKeyboardTracking(True)
        self.spinBox_min_bbbv.setProperty("showGroupSeparator", False)
        self.spinBox_min_bbbv.setMinimum(0)
        self.spinBox_min_bbbv.setMaximum(9999)
        self.spinBox_min_bbbv.setProperty("value", 0)
        self.spinBox_min_bbbv.setObjectName("spinBox_min_bbbv")
        self.spinBox_pixsize = QtWidgets.QSpinBox(Form)
        self.spinBox_pixsize.setGeometry(QtCore.QRect(400, 20, 132, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_pixsize.sizePolicy().hasHeightForWidth())
        self.spinBox_pixsize.setSizePolicy(sizePolicy)
        self.spinBox_pixsize.setMinimumSize(QtCore.QSize(132, 0))
        self.spinBox_pixsize.setMaximumSize(QtCore.QSize(132, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_pixsize.setFont(font)
        self.spinBox_pixsize.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_pixsize.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_pixsize.setFrame(True)
        self.spinBox_pixsize.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_pixsize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_pixsize.setKeyboardTracking(True)
        self.spinBox_pixsize.setProperty("showGroupSeparator", False)
        self.spinBox_pixsize.setMinimum(1)
        self.spinBox_pixsize.setMaximum(200)
        self.spinBox_pixsize.setProperty("value", 20)
        self.spinBox_pixsize.setObjectName("spinBox_pixsize")
        self.label_pixsize = QtWidgets.QLabel(Form)
        self.label_pixsize.setGeometry(QtCore.QRect(290, 20, 100, 32))
        self.label_pixsize.setMinimumSize(QtCore.QSize(100, 0))
        self.label_pixsize.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_pixsize.setFont(font)
        self.label_pixsize.setScaledContents(False)
        self.label_pixsize.setWordWrap(False)
        self.label_pixsize.setObjectName("label_pixsize")
        self.spinBox_auto_replay = QtWidgets.QSpinBox(Form)
        self.spinBox_auto_replay.setGeometry(QtCore.QRect(180, 292, 132, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_auto_replay.sizePolicy().hasHeightForWidth())
        self.spinBox_auto_replay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_auto_replay.setFont(font)
        self.spinBox_auto_replay.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_auto_replay.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"color: #3d3d3d;")
        self.spinBox_auto_replay.setFrame(True)
        self.spinBox_auto_replay.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_auto_replay.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_auto_replay.setKeyboardTracking(True)
        self.spinBox_auto_replay.setProperty("showGroupSeparator", False)
        self.spinBox_auto_replay.setMinimum(-1)
        self.spinBox_auto_replay.setMaximum(100)
        self.spinBox_auto_replay.setProperty("value", 30)
        self.spinBox_auto_replay.setObjectName("spinBox_auto_replay")
        self.comboBox_gamemode = QtWidgets.QComboBox(Form)
        self.comboBox_gamemode.setGeometry(QtCore.QRect(130, 20, 134, 36))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_gamemode.setFont(font)
        self.comboBox_gamemode.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox_gamemode.setStyleSheet("border-width: 2px;\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"background-color: #f4f4f4;\n"
"width:102px;\n"
"height: 32px;\n"
"color: #3d3d3d;\n"
"\n"
"")
        self.comboBox_gamemode.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_gamemode.setObjectName("comboBox_gamemode")
        self.comboBox_gamemode.addItem("")
        self.comboBox_gamemode.addItem("")
        self.comboBox_gamemode.addItem("")
        self.comboBox_gamemode.addItem("")
        self.comboBox_gamemode.addItem("")
        self.comboBox_gamemode.addItem("")
        self.comboBox_gamemode.addItem("")
        self.comboBox_gamemode.addItem("")
        self.checkBox_auto_replay = QtWidgets.QCheckBox(Form)
        self.checkBox_auto_replay.setGeometry(QtCore.QRect(40, 290, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.checkBox_auto_replay.setFont(font)
        self.checkBox_auto_replay.setToolTip("")
        self.checkBox_auto_replay.setStyleSheet("")
        self.checkBox_auto_replay.setObjectName("checkBox_auto_replay")
        self.checkBox_auto_notification = QtWidgets.QCheckBox(Form)
        self.checkBox_auto_notification.setGeometry(QtCore.QRect(40, 320, 231, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.checkBox_auto_notification.setFont(font)
        self.checkBox_auto_notification.setToolTip("")
        self.checkBox_auto_notification.setStyleSheet("")
        self.checkBox_auto_notification.setObjectName("checkBox_auto_notification")
        self.checkBox_allow_min3BV = QtWidgets.QCheckBox(Form)
        self.checkBox_allow_min3BV.setGeometry(QtCore.QRect(40, 350, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.checkBox_allow_min3BV.setFont(font)
        self.checkBox_allow_min3BV.setToolTip("")
        self.checkBox_allow_min3BV.setStyleSheet("")
        self.checkBox_allow_min3BV.setObjectName("checkBox_allow_min3BV")
        self.checkBox_allow_max3BV = QtWidgets.QCheckBox(Form)
        self.checkBox_allow_max3BV.setGeometry(QtCore.QRect(40, 380, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.checkBox_allow_max3BV.setFont(font)
        self.checkBox_allow_max3BV.setToolTip("")
        self.checkBox_allow_max3BV.setStyleSheet("")
        self.checkBox_allow_max3BV.setObjectName("checkBox_allow_max3BV")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(30, 190, 501, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.retranslateUi(Form)
        self.comboBox_gamemode.setCurrentIndex(4)
        self.horizontalSlider_transparency.valueChanged['int'].connect(self.label_transparency_percent_value.setNum) # type: ignore
        self.pushButton_no.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "游戏设置"))
        self.pushButton_yes.setText(_translate("Form", "确定"))
        self.pushButton_no.setText(_translate("Form", "取消"))
        self.label_transparency.setText(_translate("Form", "窗口透明度"))
        self.label_transparency_percent.setText(_translate("Form", "%"))
        self.checkBox_end_then_flag.setText(_translate("Form", "结束后标雷"))
        self.label_label.setText(_translate("Form", "标识："))
        self.label_race_label.setText(_translate("Form", "比赛后缀："))
        self.checkBox_filter_forever.setToolTip(_translate("Form", "勾选后永远使用筛选法埋雷，否则会智能改用调整法"))
        self.checkBox_filter_forever.setText(_translate("Form", "永远使用筛选法埋雷（不推荐）"))
        self.label_auto_replay_percent.setText(_translate("Form", "%"))
        self.checkBox_autosave_video.setToolTip(_translate("Form", "勾选后永远使用筛选法埋雷，否则会智能改用调整法"))
        self.checkBox_autosave_video.setText(_translate("Form", "自动保存录像（推荐）"))
        self.label_country.setText(_translate("Form", "国家："))
        self.label_gamemode.setText(_translate("Form", "游戏模式："))
        self.label_pixsize.setText(_translate("Form", "方格边长："))
        self.comboBox_gamemode.setItemText(0, _translate("Form", "标准"))
        self.comboBox_gamemode.setItemText(1, _translate("Form", "Win7"))
        self.comboBox_gamemode.setItemText(2, _translate("Form", "强无猜"))
        self.comboBox_gamemode.setItemText(3, _translate("Form", "弱无猜"))
        self.comboBox_gamemode.setItemText(4, _translate("Form", "竞速无猜"))
        self.comboBox_gamemode.setItemText(5, _translate("Form", "准无猜"))
        self.comboBox_gamemode.setItemText(6, _translate("Form", "强可猜"))
        self.comboBox_gamemode.setItemText(7, _translate("Form", "弱可猜"))
        self.checkBox_auto_replay.setText(_translate("Form", "自动重开："))
        self.checkBox_auto_notification.setText(_translate("Form", "允许记录弹窗（推荐）"))
        self.checkBox_allow_min3BV.setText(_translate("Form", "3BV最小值："))
        self.checkBox_allow_max3BV.setText(_translate("Form", "3BV最大值："))
